<?php

namespace ContainerIzPgItR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_UriVariables_Transformer_ApiResourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.uri_variables.transformer.api_resource' shared service.
     *
     * @return \ApiPlatform\Metadata\UriVariableTransformer\ApiResourceUriVariableTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'metadata'.\DIRECTORY_SEPARATOR.'UriVariableTransformerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'metadata'.\DIRECTORY_SEPARATOR.'UriVariableTransformer'.\DIRECTORY_SEPARATOR.'ApiResourceUriVariableTransformer.php';

        $a = ($container->privates['api_platform.api.identifiers_extractor'] ?? self::getApiPlatform_Api_IdentifiersExtractorService($container));

        if (isset($container->privates['api_platform.uri_variables.transformer.api_resource'])) {
            return $container->privates['api_platform.uri_variables.transformer.api_resource'];
        }

        $instance = new \ApiPlatform\Metadata\UriVariableTransformer\ApiResourceUriVariableTransformer($a, ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)));

        if (isset($container->privates['api_platform.uri_variables.transformer.api_resource'])) {
            return $container->privates['api_platform.uri_variables.transformer.api_resource'];
        }

        return $container->privates['api_platform.uri_variables.transformer.api_resource'] = $instance;
    }
}
