<?php

namespace ContainerIzPgItR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_ApiPlatform_Openapi_FactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_jwt_authentication.api_platform.openapi.factory' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'OpenApiFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'jwt-authentication-bundle'.\DIRECTORY_SEPARATOR.'OpenApi'.\DIRECTORY_SEPARATOR.'OpenApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Serializer'.\DIRECTORY_SEPARATOR.'NormalizeOperationNameTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'TypeFactoryTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'openapi'.\DIRECTORY_SEPARATOR.'Factory'.\DIRECTORY_SEPARATOR.'OpenApiFactory.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'state'.\DIRECTORY_SEPARATOR.'Pagination'.\DIRECTORY_SEPARATOR.'PaginationOptions.php';

        $a = ($container->privates['api_platform.doctrine.orm.metadata.resource.metadata_collection_factory'] ?? self::getApiPlatform_Doctrine_Orm_Metadata_Resource_MetadataCollectionFactoryService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }
        $b = ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }
        $c = ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? self::getApiPlatform_Metadata_Property_MetadataFactory_CachedService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }
        $d = ($container->privates['api_platform.json_schema.backward_compatible_schema_factory'] ?? $container->load('getApiPlatform_JsonSchema_BackwardCompatibleSchemaFactoryService'));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }
        $e = ($container->privates['api_platform.filter_locator'] ?? self::getApiPlatform_FilterLocatorService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }
        $f = ($container->privates['api_platform.router'] ?? self::getApiPlatform_RouterService($container));

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }

        $instance = new \Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory(new \ApiPlatform\OpenApi\Factory\OpenApiFactory(($container->privates['api_platform.metadata.resource.name_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_NameCollectionFactory_CachedService($container)), $a, $b, $c, $d, $e, $container->parameters['api_platform.formats'], ($container->privates['api_platform.openapi.options'] ?? $container->load('getApiPlatform_Openapi_OptionsService')), new \ApiPlatform\State\Pagination\PaginationOptions(true, 'page', false, 'itemsPerPage', false, 'pagination', 30, 30, false, false, 'partial'), $f, $container->parameters['api_platform.error_formats']), '/api/login_check', 'username', 'password');

        if (isset($container->privates['lexik_jwt_authentication.api_platform.openapi.factory'])) {
            return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'];
        }

        return $container->privates['lexik_jwt_authentication.api_platform.openapi.factory'] = $instance;
    }
}
