<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzPgItR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzPgItR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIzPgItR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIzPgItR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIzPgItR\App_KernelDevDebugContainer([
    'container.build_hash' => 'IzPgItR',
    'container.build_id' => 'e08ddd22',
    'container.build_time' => 1774546047,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzPgItR');
