<?php

namespace ContainerIzPgItR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenduListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\RenduListener' shared autowired service.
     *
     * @return \App\EventListener\RenduListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'RenduListener.php';

        return $container->privates['App\\EventListener\\RenduListener'] = new \App\EventListener\RenduListener();
    }
}
